### ISSUE TITLE
Vagrantfile should read IP address from JSON configuration file

### ISSUE THREAD

**Issue by clubdeuce** [pressboxx/pressboxx#4]

**Comment by mikeschinkel** [comment]
@clubdeuce I would rather have the command update `Vagrantfile` based on the JSON configuration.  

I'd rather minimize the work `Vagrantfile` does and have it be a configuration output artifact rather than have `Vagrantfile` do much work.  

I'm going to close this ticket as won't fix and add another one here: https://github.com/pressboxx/guest-cli/issues/32
